const containerGameSnowmanWord = "containerGameSnowmanWord";
const containerGameSnowmanWordToDiscoverMain = "containerGameSnowmanWordToDiscoverMain";
const containerGameSnowmanWordToDiscoverMainParts = "containerGameSnowmanWordToDiscoverMainParts";
const containerGameSnowmanDescriptionElements = "containerGameSnowmanDescriptionElements";
const containerGameSnowmanWordToDiscover = "containerGameSnowmanWordToDiscover";
const gameSnowmanElementWordToDiscover = "gameSnowmanElementWordToDiscover";
const gameSnowmanElementWordToDiscoverBase = "gameSnowmanElementWordToDiscoverBase";
const gameSnowmanElementWordToDiscoverVisibleColor = "gameSnowmanElementWordToDiscoverVisibleColor";